/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TunerRouteImport } from './routes/tuner'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiFetchRouteImport } from './routes/api/fetch'
import { Route as ApiAudioSearchRouteImport } from './routes/api/audio.search'

const TunerRoute = TunerRouteImport.update({
  id: '/tuner',
  path: '/tuner',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchRoute = ApiFetchRouteImport.update({
  id: '/api/fetch',
  path: '/api/fetch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioSearchRoute = ApiAudioSearchRouteImport.update({
  id: '/api/audio/search',
  path: '/api/audio/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/planos': typeof PlanosRoute
  '/tuner': typeof TunerRoute
  '/api/fetch': typeof ApiFetchRoute
  '/api/search': typeof ApiSearchRoute
  '/api/audio/search': typeof ApiAudioSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/planos': typeof PlanosRoute
  '/tuner': typeof TunerRoute
  '/api/fetch': typeof ApiFetchRoute
  '/api/search': typeof ApiSearchRoute
  '/api/audio/search': typeof ApiAudioSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/planos': typeof PlanosRoute
  '/tuner': typeof TunerRoute
  '/api/fetch': typeof ApiFetchRoute
  '/api/search': typeof ApiSearchRoute
  '/api/audio/search': typeof ApiAudioSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/planos'
    | '/tuner'
    | '/api/fetch'
    | '/api/search'
    | '/api/audio/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/planos'
    | '/tuner'
    | '/api/fetch'
    | '/api/search'
    | '/api/audio/search'
  id:
    | '__root__'
    | '/'
    | '/planos'
    | '/tuner'
    | '/api/fetch'
    | '/api/search'
    | '/api/audio/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlanosRoute: typeof PlanosRoute
  TunerRoute: typeof TunerRoute
  ApiFetchRoute: typeof ApiFetchRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiAudioSearchRoute: typeof ApiAudioSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tuner': {
      id: '/tuner'
      path: '/tuner'
      fullPath: '/tuner'
      preLoaderRoute: typeof TunerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch': {
      id: '/api/fetch'
      path: '/api/fetch'
      fullPath: '/api/fetch'
      preLoaderRoute: typeof ApiFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio/search': {
      id: '/api/audio/search'
      path: '/api/audio/search'
      fullPath: '/api/audio/search'
      preLoaderRoute: typeof ApiAudioSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlanosRoute: PlanosRoute,
  TunerRoute: TunerRoute,
  ApiFetchRoute: ApiFetchRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiAudioSearchRoute: ApiAudioSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
