/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TunerRouteImport } from './routes/tuner'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RepertoriosRouteImport } from './routes/repertorios'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MinhaAssinaturaRouteImport } from './routes/minha-assinatura'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MusicasIndexRouteImport } from './routes/musicas.index'
import { Route as MusicasIdRouteImport } from './routes/musicas.$id'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiFetchRouteImport } from './routes/api/fetch'
import { Route as ApiWebhookMercadoPagoRouteImport } from './routes/api/webhook/mercado-pago'
import { Route as ApiAudioSearchRouteImport } from './routes/api/audio.search'

const TunerRoute = TunerRouteImport.update({
  id: '/tuner',
  path: '/tuner',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RepertoriosRoute = RepertoriosRouteImport.update({
  id: '/repertorios',
  path: '/repertorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaAssinaturaRoute = MinhaAssinaturaRouteImport.update({
  id: '/minha-assinatura',
  path: '/minha-assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicasIndexRoute = MusicasIndexRouteImport.update({
  id: '/musicas/',
  path: '/musicas/',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicasIdRoute = MusicasIdRouteImport.update({
  id: '/musicas/$id',
  path: '/musicas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchRoute = ApiFetchRouteImport.update({
  id: '/api/fetch',
  path: '/api/fetch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookMercadoPagoRoute = ApiWebhookMercadoPagoRouteImport.update({
  id: '/api/webhook/mercado-pago',
  path: '/api/webhook/mercado-pago',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioSearchRoute = ApiAudioSearchRouteImport.update({
  id: '/api/audio/search',
  path: '/api/audio/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/repertorios': typeof RepertoriosRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/tuner': typeof TunerRoute
  '/api/fetch': typeof ApiFetchRoute
  '/api/search': typeof ApiSearchRoute
  '/musicas/$id': typeof MusicasIdRoute
  '/musicas/': typeof MusicasIndexRoute
  '/api/audio/search': typeof ApiAudioSearchRoute
  '/api/webhook/mercado-pago': typeof ApiWebhookMercadoPagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/repertorios': typeof RepertoriosRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/tuner': typeof TunerRoute
  '/api/fetch': typeof ApiFetchRoute
  '/api/search': typeof ApiSearchRoute
  '/musicas/$id': typeof MusicasIdRoute
  '/musicas': typeof MusicasIndexRoute
  '/api/audio/search': typeof ApiAudioSearchRoute
  '/api/webhook/mercado-pago': typeof ApiWebhookMercadoPagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/repertorios': typeof RepertoriosRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/tuner': typeof TunerRoute
  '/api/fetch': typeof ApiFetchRoute
  '/api/search': typeof ApiSearchRoute
  '/musicas/$id': typeof MusicasIdRoute
  '/musicas/': typeof MusicasIndexRoute
  '/api/audio/search': typeof ApiAudioSearchRoute
  '/api/webhook/mercado-pago': typeof ApiWebhookMercadoPagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/busca'
    | '/minha-assinatura'
    | '/perfil'
    | '/planos'
    | '/privacidade'
    | '/repertorios'
    | '/sobre'
    | '/termos'
    | '/tuner'
    | '/api/fetch'
    | '/api/search'
    | '/musicas/$id'
    | '/musicas/'
    | '/api/audio/search'
    | '/api/webhook/mercado-pago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/busca'
    | '/minha-assinatura'
    | '/perfil'
    | '/planos'
    | '/privacidade'
    | '/repertorios'
    | '/sobre'
    | '/termos'
    | '/tuner'
    | '/api/fetch'
    | '/api/search'
    | '/musicas/$id'
    | '/musicas'
    | '/api/audio/search'
    | '/api/webhook/mercado-pago'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/busca'
    | '/minha-assinatura'
    | '/perfil'
    | '/planos'
    | '/privacidade'
    | '/repertorios'
    | '/sobre'
    | '/termos'
    | '/tuner'
    | '/api/fetch'
    | '/api/search'
    | '/musicas/$id'
    | '/musicas/'
    | '/api/audio/search'
    | '/api/webhook/mercado-pago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BuscaRoute: typeof BuscaRoute
  MinhaAssinaturaRoute: typeof MinhaAssinaturaRoute
  PerfilRoute: typeof PerfilRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RepertoriosRoute: typeof RepertoriosRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  TunerRoute: typeof TunerRoute
  ApiFetchRoute: typeof ApiFetchRoute
  ApiSearchRoute: typeof ApiSearchRoute
  MusicasIdRoute: typeof MusicasIdRoute
  MusicasIndexRoute: typeof MusicasIndexRoute
  ApiAudioSearchRoute: typeof ApiAudioSearchRoute
  ApiWebhookMercadoPagoRoute: typeof ApiWebhookMercadoPagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tuner': {
      id: '/tuner'
      path: '/tuner'
      fullPath: '/tuner'
      preLoaderRoute: typeof TunerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repertorios': {
      id: '/repertorios'
      path: '/repertorios'
      fullPath: '/repertorios'
      preLoaderRoute: typeof RepertoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-assinatura': {
      id: '/minha-assinatura'
      path: '/minha-assinatura'
      fullPath: '/minha-assinatura'
      preLoaderRoute: typeof MinhaAssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musicas/': {
      id: '/musicas/'
      path: '/musicas'
      fullPath: '/musicas/'
      preLoaderRoute: typeof MusicasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musicas/$id': {
      id: '/musicas/$id'
      path: '/musicas/$id'
      fullPath: '/musicas/$id'
      preLoaderRoute: typeof MusicasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch': {
      id: '/api/fetch'
      path: '/api/fetch'
      fullPath: '/api/fetch'
      preLoaderRoute: typeof ApiFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/mercado-pago': {
      id: '/api/webhook/mercado-pago'
      path: '/api/webhook/mercado-pago'
      fullPath: '/api/webhook/mercado-pago'
      preLoaderRoute: typeof ApiWebhookMercadoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio/search': {
      id: '/api/audio/search'
      path: '/api/audio/search'
      fullPath: '/api/audio/search'
      preLoaderRoute: typeof ApiAudioSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BuscaRoute: BuscaRoute,
  MinhaAssinaturaRoute: MinhaAssinaturaRoute,
  PerfilRoute: PerfilRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RepertoriosRoute: RepertoriosRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  TunerRoute: TunerRoute,
  ApiFetchRoute: ApiFetchRoute,
  ApiSearchRoute: ApiSearchRoute,
  MusicasIdRoute: MusicasIdRoute,
  MusicasIndexRoute: MusicasIndexRoute,
  ApiAudioSearchRoute: ApiAudioSearchRoute,
  ApiWebhookMercadoPagoRoute: ApiWebhookMercadoPagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
